import { supabase } from './supabaseClient';

const insertData = async () => {
  try {
    // Insert categories
    const categoryMap = {};
    const categories = ['Hospital Services', 'Education'];
    for (const cat of categories) {
      const { data, error } = await supabase
        .from('categories')
        .upsert({ name: cat }, { onConflict: 'name' })
        .select('id');
      if (error) throw error;
      categoryMap[cat] = data[0].id;
    }

    // Insert provinces
    const provinceMap = {};
    const provinces = [
      'WESTERN',
      'Northern',
      'SOUTHERN',
      'Central',
      'Eastern',
      'Uva',
      'North Western', // Fixed typo from 'NORTH WESTEN'
      'SABARAGAMUWA',
      'North Central'
    ];
    for (const prov of provinces) {
      const { data, error } = await supabase
        .from('provinces')
        .upsert({ name: prov }, { onConflict: 'name' })
        .select('id');
      if (error) throw error;
      provinceMap[prov] = data[0].id;
    }

    // Insert districts
    const districtMap = {};
    const districtsByProv = {
      'WESTERN': ['Colombo', 'Kaluthara', 'Gampaha'],
      'Northern': ['Kilinochchi', 'Vavuniya', 'Mullaitivu', 'Mannar', 'Jaffna'],
      'SOUTHERN': ['Galle', 'Mathara', 'Hambanthota'],
      'Central': ['Kandy', 'Nuwara Eliya', 'Mathale'],
      'Eastern': ['Trincomalee –', 'Batticaloa -', 'Ampara', 'Kalmunai  -'],
      'Uva': ['Badulla', 'Monaragala'],
      'North Western': ['Kurunagala', 'Puttalama'],
      'SABARAGAMUWA': ['Kegalle', 'Rathnapura'],
      'North Central': ['Polonnaruwa', 'Anuradhapura']
    };
    for (const prov in districtsByProv) {
      for (const dist of districtsByProv[prov]) {
        const { data, error } = await supabase
          .from('districts')
          .upsert({ name: dist, province_id: provinceMap[prov] }, { onConflict: 'name' })
          .select('id');
        if (error) throw error;
        districtMap[`${prov}-${dist}`] = data[0].id;
      }
    }

    // Insert institutions
    const instData = [
      { province: null, district: null, name: 'Apeksha Hospital (National Cancer Institute, Maharagama)', category: 'Hospital Services' },
      { province: null, district: null, name: 'Ashraff Memorial Hospital (Base Hospital, Kalmunai South)', category: 'Hospital Services' },
      { province: null, district: null, name: 'Base Hospital Akkaraipattu', category: 'Hospital Services' },
      { province: null, district: null, name: 'Base Hospital Beruwala', category: 'Hospital Services' },
      { province: null, district: null, name: 'Base Hospital Colombo East (Mulleriyawa)', category: 'Hospital Services' },
      { province: null, district: null, name: 'Base Hospital Gampola', category: 'Hospital Services' },
      { province: null, district: null, name: 'Base Hospital Kalmunai North', category: 'Hospital Services' },
      { province: null, district: null, name: 'Base Hospital Kanthale', category: 'Hospital Services' },
      { province: null, district: null, name: 'Castle Street Hospital for Women', category: 'Hospital Services' },
      { province: null, district: null, name: 'De Soysa Maternity Hospital', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Ampara', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Chilaw', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Embilipitiya', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Hambanthoto', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Kegalle', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Matale', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Matara and Hospital of Godagama', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Nawalapitiya', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Negombo', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Nuwara Eliya', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Polonnaruwa', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital', category: 'Hospital Services' },
      { province: null, district: null, name: 'District General Hospital Trincomalee', category: 'Hospital Services' },
      { province: null, district: null, name: 'Divisional Hospital Aluthgama', category: 'Hospital Services' },
      { province: null, district: null, name: 'Family Health Bureau', category: 'Hospital Services' },
      { province: null, district: null, name: 'German – Sri Lanka Friendship Hospital for Woman (Teaching) Galle', category: 'Hospital Services' },
      { province: null, district: null, name: 'Institute of Oral Health – Maharagama', category: 'Hospital Services' },
      { province: null, district: null, name: 'Lady Ridgeway Hospital', category: 'Hospital Services' },
      { province: null, district: null, name: 'Leprosy Hospital Handala', category: 'Hospital Services' },
      { province: null, district: null, name: 'Leprosy Hospital Mantivu', category: 'Hospital Services' },
      { province: null, district: null, name: 'Medical Research Institute', category: 'Hospital Services' },
      { province: null, district: null, name: 'Ministry Of Health Head Office – Renal Disease Prevention and Research Unit', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Blood Transfusion Service', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Cancer Control Programme', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Dental Hospital (Teaching)', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Eye Hospital', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Hospital Galle', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Hospital Kandy', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Hospital for Respiratory Diseases (Chest Hospital Welisara)', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Hospital Sri Lanka', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Institute for Nephrology, Dialysis and Transplantation', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Institute of Infectious Diseases (IDH)', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Institute of Mental Health Angoda (Mulleriya New Town)', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Nephrology Specialized Hospital, Polonnaruwa', category: 'Hospital Services' },
      { province: null, district: null, name: 'National Programme for Tuberculosis Control and Chest Diseases', category: 'Hospital Services' },
      { province: null, district: null, name: 'National STD / AIDS Control Programme', category: 'Hospital Services' },
      { province: null, district: null, name: 'Port Health Office – Medical Research Institute  (MRI)', category: 'Hospital Services' },
      { province: null, district: null, name: 'Rehabilitation Hospital Ragama', category: 'Hospital Services' },
      { province: null, district: null, name: 'Sexually Transmitted Disease Clinic Mahamodara', category: 'Hospital Services' },
      { province: null, district: null, name: 'Sirimavo Bandaranayake Specialized Children’s Hospital', category: 'Hospital Services' },
      { province: null, district: null, name: 'Sri Lanka Parliament Medical Centre', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Anuradhapura', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Badulla', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Batticaloa', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Colombo North (Ragama)', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Colombo South (Kalubowila)', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Jaffna', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Kalutara', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Kuliyapitiya', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Kurunegala', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Peradeniya', category: 'Hospital Services' },
      { province: null, district: null, name: 'Teaching Hospital Ratnapura', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Colombo', name: 'BH Homagama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Colombo', name: 'DH Wethara', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Colombo', name: 'DH Padukka', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Colombo', name: 'DH Talangama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Colombo', name: 'DH Athurugiriya', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Colombo', name: 'DH Maligawatta', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'BH Agalawaththa', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'BH Aluthgama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Aluthgama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Baduraliya', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Bandaragama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Beruwala', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Darga Town', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Bulathsinhala', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Dodangoda', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Galpatha', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Halthota', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Ingiriya', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Iththapana', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Katugahahena', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Mathugama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Migahathanna', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Moronthuduwa', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Nabowa', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Warakagoda', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Aluthgama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Kaluthara', name: 'DH Pibura', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Divlapitiya', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Dompe', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Ja Ela', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Pamunugama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Radawana', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Udupila', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH akaragama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Bokalagama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Kadana', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Biyagama', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Malwathuhiripitiya', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Kadana', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'DH Minuwangoda', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'PMCU Alawala', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'PMCU Bemmulla', category: 'Hospital Services' },
      { province: 'WESTERN', district: 'Gampaha', name: 'BH Kiribathgoda', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'DGH Kilinochchi', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'BH Mulankavil', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'DH Akkarayankulam', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'DH Poonakary', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'DH Palai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'DH Tharmapuram', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'DH Palai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Kilinochchi', name: 'Chest Clinic Kilinochchi', category: 'Hospital Services' },
      { province: 'Northern', district: 'Vavuniya', name: 'DGH Vavuniya', category: 'Hospital Services' },
      { province: 'Northern', district: 'Vavuniya', name: 'BH Chettikulam', category: 'Hospital Services' },
      { province: 'Northern', district: 'Vavuniya', name: 'DH Nedunkerny', category: 'Hospital Services' },
      { province: 'Northern', district: 'Vavuniya', name: 'Chest Clinic Vavuniya', category: 'Hospital Services' },
      { province: 'Northern', district: 'Vavuniya', name: 'STD Clinic Vavuniya', category: 'Hospital Services' },
      { province: 'Northern', district: 'Vavuniya', name: 'CKD Uniy', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'DGH Mullaitivu', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'BH Mankulam', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'Rehabilitation Care Hospital BH Mankulam', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'BH Mallavi', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'BH Puthukkudiyiruppu', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'DH Sampathnuwara', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'DH Oddisuddan', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'DH Naddankandal', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'DH Unappulava', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mullaitivu', name: 'Chest Clinic Mullaitivu', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'DGH Mannar', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'Mental Health Acute Centre DGH Mannar', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'DH Chilawathurani', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'DH Adampan', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'BH Murunkan', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'DH Talaimannar', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'DH Pesalai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'DH Vidaththaltivu', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'Chest Clinic Mannar', category: 'Hospital Services' },
      { province: 'Northern', district: 'Mannar', name: 'STD Mannar', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'BH Point Pedro', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'BH Tellipalai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'Cancer Unit BH Thellipalai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'BH Chavakachcheri', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'BH Kayts', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Atchuveli', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Chankanai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Kapay', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Valvettiyhurai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Velanai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Delft', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Karainagar', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'DH Maruthankerni', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'Chest Clinic – Pannai (Jaffna)', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'STD Jaffna', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'Mental Health Acute Centre BH Tellipalai', category: 'Hospital Services' },
      { province: 'Northern', district: 'Jaffna', name: 'Mental Health Acute Centra BH Point Pedro', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'BH Elpitiya', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'BH Udugama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Ahangama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Ambalangoda', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Baddegama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Benthota', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Batapola', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Habaraduwa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Hikkaduwa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Hiniduma', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Imadoowa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Iduruwa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Borakanda', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Unawatuna', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Urumangashandiya', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Waduraba', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Rathgama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Arachchikanda', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Nagoda', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Neluwa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Niyagama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Galle', name: 'DH Opatha', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'BH Deniyaya', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'BH Kaburupitiya', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Akurassa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Deiyandara', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Dikwella', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Narawelpita', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Gangodagama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH kirinda', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Mawarala', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Morawaka', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Urubokka', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Urugamuwa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Hakmana', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'DH Imaduwa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Mathara', name: 'STD Clinic Matara', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'BH Thissamarama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'BH Thangalla', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'BH Walasmulla', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Ambalanthota', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Agunakolapalassa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DG Beliaththa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Beragama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH gatamanna', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Goonadeniya', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Dikwalla', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Debarawewa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Kariyamadiththa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Kirama', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Kirinda', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Lunugamwehera', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Middeniya', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Nakulugamuwa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Rathna', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Sooriyawewa', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Uduwila', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Weerakatiya', category: 'Hospital Services' },
      { province: 'SOUTHERN', district: 'Hambanthota', name: 'DH Katuwana', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'Rehabilitation Hospital Digana', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Akurana', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Morayaya', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Madawala', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Manikhinna', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Delthota', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Dolosbage', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Dunhida', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Galagedara', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Galaha', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Galpihilla', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Gelioya', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Hasalaka', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Hathaaraliyadda', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Jambugaspitiya', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Kadugannawa', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Katugasthota', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Kolongoda', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Kotaligoda', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Kuruduwatta', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Madolkale', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Morahena', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Naramwala', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Pamunuwa', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Panwolathanna', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Pussallawa', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Sangarajapura', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Thalathuoya', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Thiththpajjala', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Ududumbara', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Uduwela', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Ulapane', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Waththepola', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Waththegama', category: 'Hospital Services' },
      { province: 'Central', district: 'Kandy', name: 'DH Yakgahapitiya', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'Chest Clinic Nuwaraeliya', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'Sexually Transmitted Disease Clinic Nuwara Eliya', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Hatton Dikoya', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Rikillagaskada', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Bogawanthalawa', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Kotagala', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Watawala', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Lidula', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Kothmale', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Agarapathana', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Ginigathhena', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Dayagama', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Hanguranketha', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Gonapitiya', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Mooloya', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Gonaganthanna', category: 'Hospital Services' },
      { province: 'Central', district: 'Nuwara Eliya', name: 'DH Nildandahinna', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Aluthwewa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Aluvihara', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Bandarapolwaththa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Dewahoowa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Dullawa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH elkaduwa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Galewela', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Gammaduwa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Gurubabila', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Hadungamuwa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Halthota Amuna', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Hettipola', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Ilukkubura', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Kalundawa', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Kongahawela', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Laggala Pallegama', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Leliambe', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Lendora', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Madipola', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Muwandeniya', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Nalanda', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Opatha', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'Ovilikanda', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Paldeniya', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Pelpola', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Ranthota', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Sigiriya', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Ukuwela', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Vewalwala', category: 'Hospital Services' },
      { province: 'Central', district: 'Mathale', name: 'DH Yatiwatta', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'BH Muthur', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'BH Kinniya', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'BH Pulmoddai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Padavisripura', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Thammpalagamam', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Gomarankadawala', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Kilivetty', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Kuchchaveli', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Nilaveli', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Serunuwara', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Eachchalampattu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Thoppur', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Seruwila', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Mahadivulwrwa', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Sampoor', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Wan-Ela', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'DH Selvanayagapuram', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'PMCU Kachchaikodithivu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'PMCU Morawewa', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'PMCU Mullipothanai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'Chest Clinic', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'STD Clinic', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'CKD Unit Screening Centre Padavisisripura', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'CKD Unit Screening Center Gomarankadawala', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Trincomalee –', name: 'Mental Health Resource Center', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'BH Kaluwanchikudy', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'BH Valaichenai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'BH Kaththankudy', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'BH Eravur', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Arayampathy', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Peryakallar', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Mahiladithivu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Chenkalady', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Meeravodai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Vakarai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Mavadivembu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH  Karadiyanaru', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Santhiveli', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Kathiraveli', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Palamunai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Thuraineelavanai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Palukamam', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Mandur', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Mandur', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Mandapathady', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Navatkadu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Cheddipalayam', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'DH Palameenmadu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'PMCU Thiraimadu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'Chest Clinic', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'STD Clinic Batticaloa', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Batticaloa -', name: 'Mental Health Rehabilitation Centre', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'BH Dehiyatthakandiya', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'BH Maha Oya', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'DH Padiyathalawa', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'DH Damana', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'DH Lahugala', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'DH Panama', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'DH Senarathpura', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'DH Thottama', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'DH Wadinagala', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'Chest Clinic', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'STD Clinic', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Ampara', name: 'Mental Health Resource Center', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'BH Samanathurai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'BH Pottuvil', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'BH Ninthavur', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'BH THirukovil', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Sainthamaruthu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Akkaraipattu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Maruthamunai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Karaithivu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Addalachenai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Palamunai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Oluvil', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Deegavapiya', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Central Camp', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Irakkamam', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Panankadu', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Malwatta', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Annamalai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'DH Sennel Kiramam', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'PMCU Komari', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'PMCU Ullai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'PMCU Periyaneelavanai', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'Chest Clinic', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'STD Clinic', category: 'Hospital Services' },
      { province: 'Eastern', district: 'Kalmunai  -', name: 'Mental Health Resourse Center', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'BH Welimada', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Bandarawela', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Passara', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Bibilegama', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Girandurukotte', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Haputhale', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Koslanda', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Lahugala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Kandaketiya', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Lunugala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Meegahakiula', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Matigahathanna', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Uwaparanagama', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Demodara', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Boralanda', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Haldummulla', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Nadungamuwa', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Bogahakubura', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Robery', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Sprinvelly', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Dambana', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Dambethama', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'BH Wallawaya', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'BH Siyabalanduwa', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Buttala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Badalkumbura', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Inginiyagala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Katharagama', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Handapanagala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Ethimale', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Hambegamuwa', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Pitakumbura', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Dambagalla', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Higurukaduwa', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Sewanagala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Badulla', name: 'DH Okkanpitiya', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'BH Bibile', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Madagama', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Thanamalwila', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Siyabalanduwa', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Wallawaya', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Badalkubura', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Buththala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Dabagalla', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Ethimale', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Habegamuwa', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Hadapanagala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Higurukaduwa', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Iginiyagala', category: 'Hospital Services' },
      { province: 'Uva', district: 'Monaragala', name: 'DH Katharagama', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'BH Dabadeniya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'BH Galgamuwa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'TH Kuliyapitiya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'BH Nikawaratiya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'BH Polpithigama', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Alawwa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Abanpola', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Bingiriya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Doonaakadeniya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Gokaralla', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Gonigoda', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Hettipola', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Hiripitiya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Wallawa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Katupotha', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'Chest Hospital Kurunagala', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Kobeigane', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Mahananneriya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Maho', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Mawathagama', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Megalewa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Naramwala', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Polgahawela', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Rajanganaya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Rididgama', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Sadalankawa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Thalanpitiya', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Wariyapola', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Kadanegedara', category: 'Hospital Services' },
      { province: 'North Western', district: 'Kurunagala', name: 'DH Polpithigama', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'BH Marawila', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'BH Puttalama', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'DH Anamaduwa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'DH Anandawilanduwa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'DH Dankotuwa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'DH Galmuruwa', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'DH Naramwala', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'DH Luniwila', category: 'Hospital Services' },
      { province: 'North Western', district: 'Puttalama', name: 'DH Mundalama', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'BH Karawanella', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'BH Mawanalla', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Algama', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Amithirigala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Aranayaka', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Atala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Beligala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Bulathkohupitiya', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Dedugala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Daraniyagala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Kiriporuwa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Gonagaldeniya', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Halgolla', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Hemmathagama', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Higuralakanda', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Kithulgala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Mahapallegama', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Rabukkana', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Sapumalkanda', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Kegalle', name: 'DH Udugoda', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'BH Kahawaththa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'BH Kalawana', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Alupotha', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Ayagama', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Belihulloya', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Chandrikawwewa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Mahawalathenna', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Marathenna', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Niwithigala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Omalpe', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Dabag', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Ahaliyagoda', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Ranwala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Eraththa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Gallalla', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Gilimale', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Hunuwala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Godakawela', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH kalthota', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Kiribathgala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Kiruella', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Kiriporuwa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Kolonna', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Pallebadda', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Palm Kotte', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Palmadulla', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Pothupitiya', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Rakwana', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Rassagala', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Sooriyawewa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Teppanawa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Udawalawa', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Weligepola', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Waragama', category: 'Hospital Services' },
      { province: 'SABARAGAMUWA', district: 'Rathnapura', name: 'DH Niwithigala', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'BH Madirigiriya', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'BH Walikanda', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Aralaganwila', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Aththanakadawala', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Bakamuna', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Diyabeduma', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Galamuna', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Higurakgoda', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Jayanthipura', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Mananpitiya', category: 'Hospital Services' },
      { province: 'North Central', district: 'Polonnaruwa', name: 'DH Pulasthigama', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'BH Kabithigollawa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'BH Padawiya', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'BH Thabuththegama', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Adiyagala', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Elayapaththuwa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Eppawala', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Galenbidunuwewa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Galnewa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Habarana', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Horowpathana', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Mihinthale', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Nachaduwa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Nelubawa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Nochchiyagama', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Paranagaswewa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Rajanganaya Trach 11', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Huruluwewa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Kahatagasdigiliya', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Kalawewa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Kalachiya', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH kapugollawa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Kakirawa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Mahawilachchiya', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Maradankadawala', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Madawachchiya', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Rabewa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Rajanganaya Tr 5', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Rathmalgahawewa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Senapura', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Thalawa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Sampathnuwara', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Thammannawa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Thanthirimale', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'DH Elayapaththuwa', category: 'Hospital Services' },
      { province: 'North Central', district: 'Anuradhapura', name: 'Ayurweda Hospital Anuradapura', category: 'Hospital Services' },
      { province: null, district: null, name: 'NTS Kandana', category: 'Education' },
      { province: null, district: null, name: 'NTS Colombo', category: 'Education' },
      { province: null, district: null, name: 'NTS  Anuradhapura', category: 'Education' },
      { province: null, district: null, name: 'NTS Hambantota', category: 'Education' },
      { province: null, district: null, name: 'NTS Jaffna', category: 'Education' },
      { province: null, district: null, name: 'NTS Vavuniya', category: 'Education' },
      { province: null, district: null, name: 'NTS Ampara', category: 'Education' },
      { province: null, district: null, name: 'NTS Badulla', category: 'Education' },
      { province: null, district: null, name: 'NTS Batticaloa', category: 'Education' },
      { province: null, district: null, name: 'NTS Galle', category: 'Education' },
      { province: null, district: null, name: 'NTS Kalutara', category: 'Education' },
      { province: null, district: null, name: 'NTS Kandy', category: 'Education' },
      { province: null, district: null, name: 'NTS Kurunagala', category: 'Education' },
      { province: null, district: null, name: 'NTS Matara', category: 'Education' },
      { province: null, district: null, name: 'NTS Mulleriyawa', category: 'Education' },
      { province: null, district: null, name: 'NTS Rathnapura', category: 'Education' },
      { province: null, district: null, name: 'NTS Post Basic Colombo', category: 'Education' }
    ];
    for (const inst of instData) {
      const p_id = inst.province ? provinceMap[inst.province] : null;
      const d_id = inst.district ? districtMap[`${inst.province}-${inst.district}`] : null;
      const c_id = categoryMap[inst.category];
      const { error } = await supabase
        .from('institutions')
        .insert({ name: inst.name, category_id: c_id, province_id: p_id, district_id: d_id });
      if (error) console.error(error);
    }
    console.log('Data inserted successfully');
  } catch (error) {
    console.error('Error inserting data:', error);
  }
};

insertData();